#!/bin/sh

set -e

CURR_DIR=$(cd "$(dirname "$0")" && pwd)

RED='\033[0;31m'
LIGHT_RED='\033[0;91m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RESET='\033[0m'

await_input()
{
    echo -e "Press any key to continue..."
    while true; do
        read -rsn1 key
        if [ -n "$key" ]; then
            break
        fi
    done
}

clean_proj()
{
    rm -rf autom4te.cache aclocal.m4 configure config.h.in config.h \
        config.log config.status Makefile Makefile.in build .deps .libs \
        *.o *.lo *.la shorkauto stamp-h1 .dirstamp libtool m4/libtool.m4 \
        m4/ltoptions.m4 m4/ltsugar.m4 m4/ltversion.m4 m4/lt~obsolete.m4 \
        autoreconf.log configure.log make.log autoconf-plain.log src/.deps \
        src/.libs src/*.o src/*.lo src/.dirstamp
}

die()
{
    printf "${RED}FAIL: $1${RESET}...\n"  >&2
    exit 1
}



cd "$CURR_DIR"
clean_proj

grep -v '^dnl SHORK Autools Test marker$' configure.ac >configure.ac.tmp
mv configure.ac.tmp configure.ac

printf "${GREEN}Testing autoreconf -fi (m4 + aclocal + libtoolize + automake + autoconf)${RESET}...\n"
autoreconf -fi >autoreconf.log 2>&1 || { cat autoreconf.log; die "autoreconf -fi"; }
[ -x ./configure ] && [ -f Makefile.in ] || die "configure/Makefile.in not generated"

printf "${GREEN}Testing ./configure${RESET}...\n"
./configure >configure.log 2>&1 || { cat configure.log; die "./configure"; }

printf "${GREEN}Testing make (libtool builds libshork.la)${RESET}...\n"
make >make.log 2>&1 || { cat make.log; die "make"; }
[ -f .libs/libshork.a ] || [ -f libshork.la ] || die "libtool library not built"

printf "${GREEN}Running the program...${RESET}...\n"
[ -x ./shorkauto ] || die "shorkauto missing"
OUTPUT=$(./shorkauto) || die "shorkauto exited nonzero (output: $OUTPUT)"
[ "$OUTPUT" = "Hello, SHORK!" ] || die "unexpected output: $OUTPUT"

printf "${GREEN}Testing autoconf...${RESET}...\n"
echo "dnl SHORK Autools Test marker" >>configure.ac
rm -f configure
autoconf >autoconf-plain.log 2>&1 || { cat autoconf-plain.log; die "autoconf (standalone)"; }
[ -x ./configure ] || die "configure not regenerated by autoconf"
