AC_PREREQ([2.73])
AC_INIT([SHORK Autools Test], [1.0], [sharksibmstuff@gmail.com])
AC_CONFIG_MACRO_DIR([m4])
AC_CONFIG_AUX_DIR([build])
AC_CONFIG_SRCDIR([src/main.c])
AC_CONFIG_HEADERS([config.h])
AM_INIT_AUTOMAKE([foreign -Wall -Werror subdir-objects])

AC_PROG_CC
AM_PROG_AR
LT_INIT([disable-shared])

SHORK_CHECK_GREETING

AC_CONFIG_FILES([Makefile])
AC_OUTPUT
