#!/bin/sh

# Mount core file systems
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs tmpfs /mnt
mount -t tmpfs tmpfs /tmp

# Populate /dev from sysfs
mdev -s

[ -r /etc/hostname ] && hostname "$(cat /etc/hostname)"

# Prepare to show the welcome banner
clear

# Show welcome banner and OS name
if [ -f /banners/welcome ]; then
    COLS=80
    BANNER_WIDTH=31
    BUFFER=""
    
    TOTAL_PAD=$((COLS - BANNER_WIDTH))
    RIGHT_PAD=$((TOTAL_PAD / 2))
    LEFT_PAD=$((TOTAL_PAD - RIGHT_PAD))

    # Print top border
    BUFFER="$(printf "%*s\n" "$COLS" '')"

    while IFS= read -r line; do
        BUFFER="${BUFFER}$(printf "%*s%s%*s\n" "$LEFT_PAD" '' "$line" "$RIGHT_PAD" '')"
    done < banners/welcome
    BUFFER="${BUFFER}$(printf "%*s\n" "$COLS" '')"

    # Show OS name
    OS="@DIST@"
    TOTAL_PAD=$((COLS - ${#OS}))
    RIGHT_PAD=$((TOTAL_PAD / 2))
    LEFT_PAD=$((TOTAL_PAD - RIGHT_PAD))
    BUFFER="${BUFFER}$(printf "%*s%s%*s\n" "$LEFT_PAD" '' "$OS" "$RIGHT_PAD" '')"

    # Show author
    AUTHOR="Kali (links.sharktastica.co.uk)"
    TOTAL_PAD=$((COLS - ${#AUTHOR}))
    RIGHT_PAD=$((TOTAL_PAD / 2))
    LEFT_PAD=$((TOTAL_PAD - RIGHT_PAD))
    BUFFER="${BUFFER}$(printf "%*s%s%*s\n" "$LEFT_PAD" '' "$AUTHOR" "$RIGHT_PAD" '')"

    # Print bottom border
    BUFFER="${BUFFER}$(printf "%*s" "$COLS" '')"

    # Set terminal to white on blue
    printf "\x1b[37;44m"
    # Print buffer
    printf "%s" "$BUFFER"
    # Reset colour
    printf "\x1b[0m"

    printf "\n\n"
fi

# Show welcome tip
printf "Welcome! Please check out \033[32mshorkhelp\033[0m to learn more about SHORK and get started."
# Public Test build disclaimer
if grep -q "PT" /etc/issue 2>/dev/null; then
    printf "\nThis is a pre-release build for testing purposes only. See \033[32mshorkhelp\033[0m's \"Public\nTest 1\" guide for more information."
fi
printf "\n\n"

# SHORKSTALL hint
if [ -f /usr/bin/shorkstall ]; then
    printf "To install SHORK to a fixed disk or floppy diskette, please run \033[32mshorkstall\033[0m.\n\n"
fi

/bin/sh -l -m
