#!/bin/sh

######################################################
## A small utility for persistently changing the    ##
## terminal foreground (font) colour                ##
######################################################
## Kali (sharktastica.co.uk)                        ##
######################################################



set -e

COLS="blue | blue_bright | cyan | cyan_bright | green | green_bright | grey | magenta | magenta_bright | red | red_bright | white | white_bright | yellow | yellow_bright"

TERM_WIDTH=$(stty size 2>/dev/null | cut -d' ' -f2)

get_current_colour()
{
    if [ -f /etc/shorkcol.conf ]; then
        . /etc/shorkcol.conf
        echo "$NAME"
    else
        echo "white"
    fi
}

if [ $# -ne 1 ]; then
    printf "Changes the terminal's foreground (font) colour.\n\n" | fold -s -w "$TERM_WIDTH"
    echo "Usage: shorkcol {$COLS}" | fold -s -w "$TERM_WIDTH"
    echo "Current colour: $(get_current_colour)"
    exit 1
fi

case "$1" in
    blue)           COL="0;34" ;;
    blue_bright)    COL="0;1;34" ;;
    cyan)           COL="0;36" ;;
    cyan_bright)    COL="0;1;36" ;;
    green)          COL="0;32" ;;
    green_bright)   COL="0;1;32" ;;
    grey)           COL="0;1;30" ;;
    magenta)        COL="0;35" ;;
    magenta_bright) COL="0;1;35" ;;
    red)            COL="0;31" ;;
    red_bright)     COL="0;1;31" ;;
    white)          COL="0;37" ;;
    white_bright)   COL="0;1;37" ;;
    yellow)         COL="0;33" ;;
    yellow_bright)  COL="0;1;33" ;;
    *)
        echo "Invalid colour: $1"
        echo "Available colours: $COLS" | fold -s -w "$TERM_WIDTH"
        exit 1
        ;;
esac

cat << EOF > /etc/shorkcol.conf
NAME="$1"
ASCII="$COL"
EOF

sed -i "s/\\\\033\[[0-9;]*m/\\\\033[${COL}m/g" /etc/profile
sed -i "s/\\\\033\[[0-9;]*m/\\\\033[${COL}m/g" /etc/init.d/rc
sed -i 's|sgr0=\\E\[0m\\E\[[0-9;]*m|sgr0=\\E[0m\\E['"$COL"'m|' /usr/share/terminfo/src/terminfo.src
tic -x -1 -o /usr/share/terminfo /usr/share/terminfo/src/terminfo.src

kill -TERM "$PPID"

echo -e "\033[${COL}mApplied colour: $1\033[0m"
