#!/bin/sh

######################################################
## /etc/init.d/rc                                   ##
######################################################
## System init script executed during boot that     ##
## mounts core file systems, ensures essential      ##
## device nodes exist, sets hostname and            ##
## environment, configures basic networking,        ##
## displays a welcome message, and begins a sync    ##
## loop to help prevent data loss on hard reboots   ##
######################################################
## Kali (sharktastica.co.uk)                        ##
######################################################



# Activate swap if present
if [ -f /etc/fstab ] && grep -q swap /etc/fstab; then
    swapon -a 2>/dev/null || true
fi

# Mount core file systems
mount -t proc  proc  /proc
mount -t sysfs sysfs /sys

# Mount devpts for pseudo-terminals
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
chmod 666 /dev/pts

# Create /var/run for utmp when multi-user
if [ -d /home ]; then
    mkdir -p /var/run /var/lock
    mount -t tmpfs tmpfs /var/run
    touch /var/run/utmp /var/run/wtmp
    chmod 664 /var/run/utmp /var/run/wtmp
    ln -sf /var/run /run
fi

# Required device nodes
[ -c /dev/ptmx ] || mknod -m 666 /dev/ptmx c 5 2
[ -c /dev/tty ]  || mknod -m 666 /dev/tty  c 5 0
[ -c /dev/tty0 ] || mknod -m 620 /dev/tty0 c 4 0
[ -c /dev/tty1 ] || mknod -m 620 /dev/tty1 c 4 1

[ -r /etc/hostname ] && hostname "$(cat /etc/hostname)"

# Load custom console font (if applicable)
if [ -f /etc/shorkset.conf ]; then
    . /etc/shorkset.conf
    if [ "$FONT_PSF" != "default" ] && [ -c /dev/tty1 ]; then
        setfont -C /dev/tty1 $FONT_PSF
    fi
fi

# Load persistent keymap (if present)
if [ -f /etc/keymap ]; then
    KM="$(cat /etc/keymap)"
    if [ -f "/usr/share/keymaps/$KM.kmap.bin" ]; then
        loadkmap < "/usr/share/keymaps/$KM.kmap.bin"
    fi
fi

export ENV=/etc/profile

# Set up networking
if [ -d /sys/class/net/eth0 ] && [ -e /sys/class/net/eth0/device ]; then
    ifconfig eth0 up
    if ifconfig eth0 2>/dev/null | grep -q "UP"; then
        udhcpc -i eth0 -n -t 3 -T 2 -s /usr/share/udhcpc/default.script > /dev/null 2>&1 &
    fi
fi

# Set up PC speaker
modprobe pcspkr 2>/dev/null || true

# Flush any ttyx seen flags
rm -f /tmp/.tty*_seen

# Prepare to show the welcome banner
clear

# Show welcome banner and OS name
if [ -f banners/welcome ]; then
    COLS=$(stty size 2>/dev/null | awk '{print $2}')
    BANNER_WIDTH=36
    BUFFER=""
    
    TOTAL_PAD=$((COLS - BANNER_WIDTH))
    RIGHT_PAD=$((TOTAL_PAD / 2))
    LEFT_PAD=$((TOTAL_PAD - RIGHT_PAD))

    # Print top border
    BUFFER="$(printf "%*s\n" "$COLS" '')"

    while IFS= read -r line; do
        BUFFER="${BUFFER}$(printf "%*s%s%*s\n" "$LEFT_PAD" '' "$line" "$RIGHT_PAD" '')"
    done < banners/welcome
    BUFFER="${BUFFER}$(printf "%*s\n" "$COLS" '')"

    # Show OS name
    OS="@DIST@"
    TOTAL_PAD=$((COLS - ${#OS}))
    RIGHT_PAD=$((TOTAL_PAD / 2))
    LEFT_PAD=$((TOTAL_PAD - RIGHT_PAD))
    BUFFER="${BUFFER}$(printf "%*s%s%*s\n" "$LEFT_PAD" '' "$OS" "$RIGHT_PAD" '')"

    # Show author
    AUTHOR="Kali (links.sharktastica.co.uk)"
    TOTAL_PAD=$((COLS - ${#AUTHOR}))
    RIGHT_PAD=$((TOTAL_PAD / 2))
    LEFT_PAD=$((TOTAL_PAD - RIGHT_PAD))
    BUFFER="${BUFFER}$(printf "%*s%s%*s\n" "$LEFT_PAD" '' "$AUTHOR" "$RIGHT_PAD" '')"

    # Print bottom border
    BUFFER="${BUFFER}$(printf "%*s" "$COLS" '')"

    # Set terminal to white on blue
    printf "\x1b[37;44m"
    # Print buffer
    printf "%s" "$BUFFER"
    # Reset colour
    printf "\x1b[0m"
fi

printf "\n"
# Padding specific for single-user use
if [ ! -d /home ]; then
    printf "\n"
fi
