#!/bin/bash

######################################################
## Gets a copy of the files each changed.txt        ##
## generated by get_changed_lore contains from a    ##
## given Linux kernel version.                      ##
######################################################
## Kali (links.sharktastica.co.uk)                  ##
######################################################



set -euo pipefail

if [[ ! -d tmp ]]; then
    echo "ERROR: No tmp/ directory. Run get_changed_lore first." >&2
    exit 1
fi

VER="v7.1"
REPO="https://raw.githubusercontent.com/torvalds/linux"
RESTORE_DIR="tmp/restored/${VER}"
mkdir -p "$RESTORE_DIR"

for CURR_DIR in tmp/*/; do
    [[ -d "$CURR_DIR" ]] || continue

    CHANGED_FILE=""
    if [[ -f "${CURR_DIR}changed.txt" ]]; then
        CHANGED_FILE="${CURR_DIR}changed.txt"
    else
        continue
    fi

    while IFS= read -r FILE_PATH || [[ -n "$FILE_PATH" ]]; do
        [[ -z "$FILE_PATH" ]] && continue
        URL="${REPO}/${VER}/${FILE_PATH}"
        DEST="${RESTORE_DIR}/${FILE_PATH}"
        mkdir -p "$(dirname "$DEST")"
        if curl -fsSL "$URL" -o "$DEST"; then
            echo "Successful: $FILE_PATH" >&2
        else
            echo "Unsuccessful: $FILE_PATH" >&2
            rm -f "$DEST"
        fi
    done < "$CHANGED_FILE"
done
