######################################################
## /etc/sudoers                                     ##
######################################################
## Main sudo plugin registration file               ##
######################################################
## Kali (links.sharktastica.co.uk)                  ##
######################################################



Plugin sudoers_policy sudoers.so
Plugin sudoers_io sudoers.so
Plugin sudoers_audit sudoers.so
